import React from 'react';
import { AlertCircle, TrendingUp, DollarSign, Home, PieChart } from 'lucide-react';
import { Alert, AlertDescription } from "@/components/ui/alert";

const ChartExplanation = ({ chartType, growthStrategy }) => {
  const explanations = {
    overview: {
      icon: TrendingUp,
      title: "Portfolio Value and Equity Growth",
      points: [
        "The blue line shows your total portfolio value, which represents the total worth of all properties",
        "The orange line shows your equity, which is the portion of the properties you actually own",
        "The gap between these lines represents your remaining mortgage debt",
        "Notice how both lines trend upward due to property appreciation and mortgage paydown"
      ]
    },
    growthPhase: {
      icon: DollarSign,
      title: "Building Phase Details",
      points: [
        "This chart provides a closer look at the portfolio value and equity during the growth phase",
        "If you chose the reinvestment strategy you can likely see small dips in equity that coincide with large jumps in you portfolio value",
        "These jumps are because our simulation shows you buying more properties as soon as you have enough equity to do so with a refinance during this phase  ",
        "The gap between these two lines is the how much principal you owe on your mortgage(s)",
      ]
    },
    properties: {
      icon: Home,
      title: "Property Acquisition Timeline",
      points: [
        "Each step up represents a new property purchase",
        growthStrategy === "reinvestment" 
          ? "Properties are bought using equity from refinancing existing properties"
          : "Properties are purchased as you save for down payments",
        "The slope between purchases shows how property values appreciate over time",
        `Your portfolio grows from ${growthStrategy === "reinvestment" 
          ? "leveraging equity in existing properties" 
          : "focusing on paying down mortgages"}`
      ]
    },
    retirementIncome: {
      icon: DollarSign,
      title: "Monthly Income During Retirement",
      points: growthStrategy === "reinvestment" 
        ? [
            "The orange line represents your monthly tax-free income from strategic refinancing",
            "Income is generated by pulling equity from your highest-equity property",
            "The variation in income reflects property appreciation and refinancing cycles",
            "This strategy allows you to access equity while maintaining property ownership"
          ]
        : [
            "Each bar shows your monthly rental income after all expenses",
            "Income grows as your mortgages get paid off",
            "Property management, taxes, and maintenance costs are already deducted",
            "This represents actual cash flow you can use in retirement"
          ]
    },
    comparison: {
      icon: PieChart,
      title: "Investment Strategy Comparison",
      points: [
        "Compare real estate returns with traditional investment options",
        "Real estate benefits from leverage and appreciation",
        "The stock market historically shows higher volatility",
        "Real estate can provide both appreciation and monthly income",
        "Different strategies suit different investment goals and risk tolerances"
      ]
    }
  };

  const getExplanation = (type) => {
    const ExplanationIcon = explanations[type].icon;
    return (
      <div className="mt-8 p-8 bg-gray-50 border border-gray-200 rounded-lg">
        <div className="flex items-center gap-4 mb-6">
          <ExplanationIcon className="h-7 w-7 text-orange-500" />
          <h4 className="text-2xl font-bold text-gray-900">
            {explanations[type].title}
          </h4>
        </div>
        <ul className="space-y-4">
          {explanations[type].points.map((point, index) => (
            <li key={index} className="flex items-start gap-4">
              <span className="text-2xl font-bold text-orange-500 mt-1">•</span>
              <span className="text-2xl text-gray-700 leading-normal">{point}</span>
            </li>
          ))}
        </ul>
      </div>
    );
  };

  return getExplanation(chartType);
};

export default ChartExplanation;